In [1]:
# !pip install ucimlrepo

In [2]:
from ucimlrepo import fetch_ucirepoimport pandas as pdimport matplotlib.pyplot as pltimport numpy as npimport seaborn as snsimport warningsfrom sklearn.preprocessing import MinMaxScalerfrom sklearn.decomposition import PCA # to visualize high dimensional datafrom sklearn.manifold import TSNEfrom sklearn.metrics import adjusted_rand_score, normalized_mutual_info_scorefrom sklearn.ensemble import RandomForestClassifierfrom sklearn.model_selection import train_test_splitfrom sklearn.metrics import accuracy_score, classification_reportwarnings.filterwarnings('ignore')

## The DATA

In [3]:
# fetch datasetbank_marketing = fetch_ucirepo(id=222)# data (as pandas dataframes)X = bank_marketing.data.featuresy = bank_marketing.data.targets# metadataprint(bank_marketing.metadata)# variable informationprint(bank_marketing.variables)

{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}
           name     role         type      demographic  \
0           age  Feature      Integer              Age
1           job  Feature  Categorical       Occupation
2       marital  Feature  Categorical   Marital Status
3     education  Feature  Categorical  Education Level
4       default  Feature       Binary             None
5       balance  Feature      Integer             None
6       housing  Feature       Binary             None
7          loan  Feature       Binary             None
8       contact  Feature  Categorical             None
9   day_of_week  Feature         Date             None
10        month  Feature         Date             None
11     duration  Feature      Integer             None
12     campaign  Feature      Integer             None
13        pdays  Feature      Integer             None
14     previous  Feature      Integer             None
15     poutcome  Feature  Categorical             None
16            y   Target       Binary             None

                                          description  units missing_values
0                                                None   None             no
1   type of job (categorical: 'admin.','blue-colla...   None             no
2   marital status (categorical: 'divorced','marri...   None             no
3   (categorical: 'basic.4y','basic.6y','basic.9y'...   None             no
4                              has credit in default?   None             no
5                              average yearly balance  euros             no
6                                   has housing loan?   None             no
7                                  has personal loan?   None             no
8   contact communication type (categorical: 'cell...   None            yes
9                        last contact day of the week   None             no
10  last contact month of year (categorical: 'jan'...   None             no
11   last contact duration, in seconds (numeric). ...   None             no
12  number of contacts performed during this campa...   None             no
13  number of days that passed by after the client...   None            yes
14  number of contacts performed before this campa...   None             no
15  outcome of the previous marketing campaign (ca...   None            yes
16          has the client subscribed a term deposit?   None             no

## Preprocessing

In [4]:
X.head()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN

In [5]:
y.dtypes

y    object
dtype: object

we have to convert our label into numerical label (right now its categorical as can be seen above)

In [6]:
X.dtypes

age             int64
job            object
marital        object
education      object
default        object
balance         int64
housing        object
loan           object
contact        object
day_of_week     int64
month          object
duration        int64
campaign        int64
pdays           int64
previous        int64
poutcome       object
dtype: object

so in addition to the labels, we have a lot of features we have to convert from categorical to numerical

## missing values

In [7]:
## MISSING DATAtotal = X.isnull().sum().sort_values(ascending=False)percent = (X.isnull().sum() / X.isnull().count()).sort_values(ascending=False).round(4)missing_data = pd.concat([total, percent], axis=1, keys=["Total", 'Percent'])missing_data.head(20)

             Total  Percent
poutcome     36959   0.8175
contact      13020   0.2880
education     1857   0.0411
job            288   0.0064
age              0   0.0000
marital          0   0.0000
default          0   0.0000
balance          0   0.0000
housing          0   0.0000
loan             0   0.0000
day_of_week      0   0.0000
month            0   0.0000
duration         0   0.0000
campaign         0   0.0000
pdays            0   0.0000
previous         0   0.0000

before decoding the categorical features, lets first handle the missing values

as can be seen from the table above, we have missing values in 4 features:

1. poutcome: missing so many values, so the best option is to just treat the missing as a category (we just fill them with 'unknown')

2. contact: for this one we only have 2 unique values ('cellular' and 'telephone'), we can't really replace the missing with any of them sense theyre missing close to a third of the values, so we just fill it with 'missing'

3. education: we're goning to fill the data with the most frequent value, becuase we're only missing about 5% of them, and also even in the real world, for the education feature of actual people this would probably work the best out of all the methods we can impelement.

4. job: the missing percentage is too small to have an impact on the performnace of our model, so we're going to do the same thing as the 'education'

In [8]:
X['poutcome'] = X['poutcome'].fillna('unknown')X['contact'] = X['contact'].fillna('unknown')

In [9]:
X['education'] = X['education'].fillna(X['education'].mode().item())X['job'] = X['job'].fillna(X['job'].mode().item())

lets check if it worked

In [10]:
## MISSING DATAtotal = X.isnull().sum().sort_values(ascending=False)percent = (X.isnull().sum() / X.isnull().count()).sort_values(ascending=False).round(4)missing_data = pd.concat([total, percent], axis=1, keys=["Total", 'Percent'])missing_data.head(20)

             Total  Percent
age              0      0.0
job              0      0.0
marital          0      0.0
education        0      0.0
default          0      0.0
balance          0      0.0
housing          0      0.0
loan             0      0.0
contact          0      0.0
day_of_week      0      0.0
month            0      0.0
duration         0      0.0
campaign         0      0.0
pdays            0      0.0
previous         0      0.0
poutcome         0      0.0

it did, so now we can go to the 'encoding' step, which means we want to convert the categorical values to numerical

## Categorical to numerical

the binary values can just get replaced with 1 and 0
the binary values as mentioned in the website provided in the assignment instructions are:

1.loan

2.housing

3.default

In [11]:
X['loan'] = X['loan'].map({'yes': 1, 'no': 0})X['housing'] = X['housing'].map({'yes': 1, 'no': 0})X['default'] = X['default'].map({'yes': 1, 'no': 0})